def BRANCH_NAME_JOB = BRANCH_NAME.replace('/', '%2F')
def BRANCH_NAME_URL = BRANCH_NAME.replace('/', '%252F')

pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/license/kubernetes.yaml'
        }
    }
    triggers {
        upstream threshold: hudson.model.Result.UNSTABLE, upstreamProjects: "SET/${BRANCH_NAME_JOB}, model/${BRANCH_NAME_JOB}, toolboxmodel/${BRANCH_NAME_JOB}, browser/${BRANCH_NAME_JOB}"
    }


    options {
        timeout(time: 5, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    stages {
        stage('Build') {
            environment {
                GITLAB_TOKEN = credentials('gitlab-api-token')
            }

            steps {
                container('python') {
                    dir('tempdir')
                    {
                        downloadFile file: 'dash.jar', url: 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST'
                        sh 'pip3 install python-gitlab'

                        // SET
                        downloadFile file: 'dependencies.zip', url: "https://ci.eclipse.org/set/job/SET/job/${BRANCH_NAME_URL}/lastSuccessfulBuild/artifact/dependencies.zip"
                        sh 'python3 ../utils/process.py dependencies.zip DEPENDENCIES.set'
                        sh 'python3 ../utils/gitlabCommit.py 27 DEPENDENCIES DEPENDENCIES.set'
                        
                        // Model
                        downloadFile file: 'dependencies.zip', url: "https://ci.eclipse.org/set/job/Model/job/${BRANCH_NAME_URL}/lastSuccessfulBuild/artifact/dependencies.zip"
                        sh 'python3 ../utils/process.py dependencies.zip DEPENDENCIES.model'
                        sh 'python3 ../utils/gitlabCommit.py 2762 DEPENDENCIES DEPENDENCIES.model'
                        
                        // Toolboxmodel
                        downloadFile file: 'dependencies.zip', url: "https://ci.eclipse.org/set/job/toolboxmodel/job/${BRANCH_NAME_URL}/lastSuccessfulBuild/artifact/dependencies.zip"
                        sh 'python3 ../utils/process.py dependencies.zip DEPENDENCIES.toolboxmodel'
                        sh 'python3 ../utils/gitlabCommit.py 2763 DEPENDENCIES DEPENDENCIES.toolboxmodel'

                        // Browser
                        downloadFile file: 'dependencies.zip', url: "https://ci.eclipse.org/set/job/browser/job/${BRANCH_NAME_URL}/lastSuccessfulBuild/artifact/dependencies.zip"
                        sh 'python3 ../utils/process.py dependencies.zip DEPENDENCIES.browser'
                        sh 'python3 ../utils/gitlabCommit.py 2764 DEPENDENCIES DEPENDENCIES.browser'

                        sh 'cp DEPENDENCIES.* ../utils'
                    }
                }
            }
        }
        stage('Deploy Snapshot')
        {
            steps {
                container('jnlp') {
                    sshagent (['projects-storage.eclipse.org-bot-ssh']) {
                        sh "ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org rm -rf /home/data/httpd/download.eclipse.org/set/nightly/${BRANCH_NAME}/utils/*"
                        sh "ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/set/nightly/${BRANCH_NAME}/utils/"
                        sh "scp -o BatchMode=yes -r utils/* genie.set@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/set/nightly/${BRANCH_NAME}/utils/"
                    }
                }
            }
        }
    }
}