pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/deploy-release/kubernetes.yaml'
        }
    }

    options {
        timeout(time: 20, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    parameters {
        string description: 'Release Version', name: 'ReleaseVersion', trim: true
    }


    stages {
        stage('Sign Release') {
            steps {
                container('github') {
                    withCredentials([usernamePassword(credentialsId: 'GitHub-BuildUser', passwordVariable: 'GITHUB_TOKEN', usernameVariable: 'GITHUB_USER')]) {
                        sh "gh release download -R eclipse-set/set ${params.ReleaseVersion} -p 'SET-*'"
                        sh 'find .'
                    }
                }
            }
        }
    }
}
