pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/deploy-release/kubernetes.yaml'
        }
    }

    options {
        timeout(time: 20, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    parameters {
        string description: 'Release Version. Format: <major>.<minor>.<patch>', name: 'ReleaseVersion', trim: true
    }


    stages {
        stage('Sign Release') {
            steps {
                container('github') {
                    withCredentials([usernamePassword(credentialsId: 'GitHub-BuildUser', passwordVariable: 'GITHUB_TOKEN', usernameVariable: 'GITHUB_USER')]) {
                        downloadFile file: 'set.zip', url: "https://github.com/eclipse-set/set/releases/download/v${params.ReleaseVersion}/SET-${params.ReleaseVersion}-win32.win32.x86_64.zip"
                        sh 'unzip set.zip'
                        sh 'find .'
                    }
                }
            }
        }
    }
}
