name: 'Setup Asciidoctor'
description: 'Installs Asciidoctor, including Hugo and Ruby'

runs:
  using: 'composite'
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
      with:
        hugo-version: '0.101.0'
        extended: true
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@cacc9f1c0b3f4eb8a16a6bb0ed10897b43b9de49 # v1.176.0
      with:
        ruby-version: 3.2
    
    - name: Install Asciidoctor
      shell: bash
      run: gem install asciidoctor
