pipeline {
  agent {
    kubernetes {
      yamlFile 'ci/build-promotion/kubernetes.yaml'
    }
  }

  options {
    timeout(time: 10, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  parameters {
    string description: 'Build to remove' name: 'name', trim: true
  }


  stages {
    stage('Remove file') {
        steps {
            container('jnlp') {
                sshagent (['projects-storage.eclipse.org-bot-ssh']) {
                    sh "ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org rm -rf /home/data/httpd/download.eclipse.org/set/nightly/${params.name}"
                }
            }
        }
    }
  }
}
