pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/kubernetes.yaml'
        }
    }
    triggers {
        upstream threshold: hudson.model.Result.UNSTABLE, upstreamProjects: 'SET/main, model/main, toolboxmodel/main, browser/main'
    }


    options {
        timeout(time: 5, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    stages {
        stage('Build') {
            steps {
                container('python') {
                    dir('tempdir')
                    {
                        sh "wget -O dash.jar 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST'"

                        // SET
                        sh "wget -O dependencies.zip 'https://ci.eclipse.org/set/job/SET/job/main/lastSuccessfulBuild/artifact/dependencies.zip' || true"
                        sh "python3 ../utils/process.py dependencies.zip DEPENDENCIES.set"
                        
                        // Model
                        sh "wget -O dependencies.zip 'https://ci.eclipse.org/set/job/Model/job/main/lastSuccessfulBuild/artifact/dependencies.zip' || true"
                        sh "python3 ../utils/process.py dependencies.zip DEPENDENCIES.model"
                        
                        // Toolboxmodel
                        sh "wget -O dependencies.zip 'https://ci.eclipse.org/set/job/toolboxmodel/job/main/lastSuccessfulBuild/artifact/dependencies.zip' || true"
                        sh "python3 ../utils/process.py dependencies.zip DEPENDENCIES.toolboxmodel"

                        // Browser
                        sh "wget -O dependencies.zip 'https://ci.eclipse.org/set/job/browser/job/main/lastSuccessfulBuild/artifact/dependencies.zip' || true"
                        sh "python3 ../utils/process.py dependencies.zip DEPENDENCIES.browser"

                        sh "ls -avl"
                        sh "cp DEPENDENCIES.* ../utils"
                    }
                }
            }
        }
        stage('Deploy Snapshot')
        {
            steps {
                container('jnlp') {
                    sshagent (['projects-storage.eclipse.org-bot-ssh']) {
                        sh "ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org rm -rf /home/data/httpd/download.eclipse.org/set/snapshots/build-utils/"
                        sh "ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/set/snapshots/build-utils/"
                        sh "scp -o BatchMode=yes -r utils/* genie.set@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/set/snapshots/build-utils/"
                    }
                }
            }
        }
    }
}