pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/pdfjs/kubernetes.yaml'
        }
    }

    options {
        timeout(time: 5, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    
    parameters {
        string defaultValue: '', description: 'Version of pdfjs to fetch', name: 'PDFJS_VERSION', trim: true
    }

    stages {
        stage('Build') {
            environment {
                GITHUB_TOKEN = credentials('github-bot-token')
            }
            steps {
                container('nodejs') {
                    dir('ci/pdfjs')
                    {
                        sh "npm ci"
                        sh "npm run build"
                        archiveArtifacts artifacts: '*.zip', allowEmptyArchive: false, fingerprint: true, onlyIfSuccessful: true
                    }
                }
            }
        }
    }
}