pipeline {
    agent {
        kubernetes {
            yamlFile 'ci/release-branch/kubernetes.yaml'
        }
    }

    options {
        timeout(time: 120, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    parameters {
        string description: 'Release Version. Format: <major>.<minor>', name: 'ReleaseVersion', trim: true
    }


    stages {
        stage('Create Release Branch') {
            steps {
                container('github') {
                    withCredentials([string(credentialsId: 'github-bot-token', variable: 'GITHUB_TOKEN')]) {
                        ghWorkflow workflow: 'create-release-branch.yml', repo: 'eclipse-set/model', citag: "[${params.ReleaseVersion}]", parameters: [version: params.ReleaseVersion]
                        ghWorkflow workflow: 'create-release-branch.yml', repo: 'eclipse-set/browser', citag: "[${params.ReleaseVersion}]", parameters: [version: params.ReleaseVersion]
                        ghWorkflow workflow: 'create-release-branch.yml', repo: 'eclipse-set/set', citag: "[${params.ReleaseVersion}]", parameters: [version: params.ReleaseVersion]
                    }
                }
            }
        }
    }
}
